source   /Users/rahulkorthiwada/Documents/practice/car-rental-system/Backend/cargo-backend/Persistence/Scripts/procedures/proc_get_body_type_v1dot0.sql
source   /Users/rahulkorthiwada/Documents/practice/car-rental-system/Backend/cargo-backend/Persistence/Scripts/procedures/proc_get_fuel_type_v1dot0.sql
source   /Users/rahulkorthiwada/Documents/practice/car-rental-system/Backend/cargo-backend/Persistence/Scripts/procedures/proc_get_model_v1dot0.sql
source   /Users/rahulkorthiwada/Documents/practice/car-rental-system/Backend/cargo-backend/Persistence/Scripts/procedures/proc_get_variant_v1dot0.sql
source   /Users/rahulkorthiwada/Documents/practice/car-rental-system/Backend/cargo-backend/Persistence/Scripts/procedures/proc_get_variant_v1dot1.sql
source   /Users/rahulkorthiwada/Documents/practice/car-rental-system/Backend/cargo-backend/Persistence/Scripts/procedures/proc_authenticate_user_details_v1dot0.sql
source   /Users/rahulkorthiwada/Documents/practice/car-rental-system/Backend/cargo-backend/Persistence/Scripts/procedures/proc_get_car_make_v1dot0.sql
source   /Users/rahulkorthiwada/Documents/practice/car-rental-system/Backend/cargo-backend/Persistence/Scripts/procedures/proc_get_location_v1dot0.sql
source   /Users/rahulkorthiwada/Documents/practice/car-rental-system/Backend/cargo-backend/Persistence/Scripts/procedures/proc_get_transmission_type_v1dot0.sql
source   /Users/rahulkorthiwada/Documents/practice/car-rental-system/Backend/cargo-backend/Persistence/Scripts/procedures/proc_logout_user_v1dot0.sql
source   /Users/rahulkorthiwada/Documents/practice/car-rental-system/Backend/cargo-backend/Persistence/Scripts/procedures/proc_create_user_v1dot0.sql
source   /Users/rahulkorthiwada/Documents/practice/car-rental-system/Backend/cargo-backend/Persistence/Scripts/procedures/proc_get_color_v1dot0.sql
source   /Users/rahulkorthiwada/Documents/practice/car-rental-system/Backend/cargo-backend/Persistence/Scripts/procedures/proc_get_make_v1dot0.sql
source   /Users/rahulkorthiwada/Documents/practice/car-rental-system/Backend/cargo-backend/Persistence/Scripts/procedures/proc_get_user_details_v1dot0.sql
source   /Users/rahulkorthiwada/Documents/practice/car-rental-system/Backend/cargo-backend/Persistence/Scripts/procedures/proc_get_variant_by_id_v1dot0.sql
source   /Users/rahulkorthiwada/Documents/practice/car-rental-system/Backend/cargo-backend/Persistence/Scripts/procedures/proc_get_add_on_v1dot0.sql
source   /Users/rahulkorthiwada/Documents/practice/car-rental-system/Backend/cargo-backend/Persistence/Scripts/procedures/proc_get_user_profile_v1dot0.sql
source   /Users/rahulkorthiwada/Documents/practice/car-rental-system/Backend/cargo-backend/Persistence/Scripts/procedures/proc_create_payment_info_v1dot0.sql
source   /Users/rahulkorthiwada/Documents/practice/car-rental-system/Backend/cargo-backend/Persistence/Scripts/procedures/proc_create_user_profile_v1dot0.sql
source   /Users/rahulkorthiwada/Documents/practice/car-rental-system/Backend/cargo-backend/Persistence/Scripts/procedures/proc_create_cart_entry_v1dot0.sql
source   /Users/rahulkorthiwada/Documents/practice/car-rental-system/Backend/cargo-backend/Persistence/Scripts/procedures/proc_create_booking_info_v1dot0.sql
source   /Users/rahulkorthiwada/Documents/practice/car-rental-system/Backend/cargo-backend/Persistence/Scripts/procedures/proc_update_booking_info_v1dot.sql
source   /Users/rahulkorthiwada/Documents/practice/car-rental-system/Backend/cargo-backend/Persistence/Scripts/procedures/proc_get_booking_info_v1dot0.sql
source   /Users/rahulkorthiwada/Documents/practice/car-rental-system/Backend/cargo-backend/Persistence/Scripts/procedures/proc_get_payment_info_v1dot0.sql
source   /Users/rahulkorthiwada/Documents/practice/car-rental-system/Backend/cargo-backend/Persistence/Scripts/procedures/proc_get_promo_code_v1dot0.sql
source   /Users/rahulkorthiwada/Documents/practice/car-rental-system/Backend/cargo-backend/Persistence/Scripts/procedures/proc_delete_variant_v1dot.sql
source   /Users/rahulkorthiwada/Documents/practice/car-rental-system/Backend/cargo-backend/Persistence/Scripts/procedures/proc_finish_booking_v1dot.sql
source   /Users/rahulkorthiwada/Documents/practice/car-rental-system/Backend/cargo-backend/Persistence/Scripts/procedures/proc_get_variant_s_v1dot0.sql
source   /Users/rahulkorthiwada/Documents/practice/car-rental-system/Backend/cargo-backend/Persistence/Scripts/procedures/proc_create_variant_v1dot0.sql
source /Users/rahulkorthiwada/Documents/practice/car-rental-system/Backend/cargo-backend/Persistence/Scripts/procedures/proc_get_booking_history_v1dot0.sql
source /Users/rahulkorthiwada/Documents/practice/car-rental-system/Backend/cargo-backend/Persistence/Scripts/procedures/proc_update_cart_date_info_v1dot.sql