source /home/rahul/Documents/code/car-rental-system/Backend/cargo-backend/Persistence/Scripts/procedures/proc_get_body_type_v1dot0.sql
source /home/rahul/Documents/code/car-rental-system/Backend/cargo-backend/Persistence/Scripts/procedures/proc_get_fuel_type_v1dot0.sql
source /home/rahul/Documents/code/car-rental-system/Backend/cargo-backend/Persistence/Scripts/procedures/proc_get_model_v1dot0.sql
source /home/rahul/Documents/code/car-rental-system/Backend/cargo-backend/Persistence/Scripts/procedures/proc_get_variant_v1dot0.sql
source /home/rahul/Documents/code/car-rental-system/Backend/cargo-backend/Persistence/Scripts/procedures/proc_authenticate_user_details_v1dot0.sql
source /home/rahul/Documents/code/car-rental-system/Backend/cargo-backend/Persistence/Scripts/procedures/proc_get_car_make_v1dot0.sql
source /home/rahul/Documents/code/car-rental-system/Backend/cargo-backend/Persistence/Scripts/procedures/proc_get_location_v1dot0.sql
source /home/rahul/Documents/code/car-rental-system/Backend/cargo-backend/Persistence/Scripts/procedures/proc_get_transmission_type_v1dot0.sql
source /home/rahul/Documents/code/car-rental-system/Backend/cargo-backend/Persistence/Scripts/procedures/proc_logout_user_v1dot0.sql
source /home/rahul/Documents/code/car-rental-system/Backend/cargo-backend/Persistence/Scripts/procedures/proc_create_user_v1dot0.sql
source /home/rahul/Documents/code/car-rental-system/Backend/cargo-backend/Persistence/Scripts/procedures/proc_get_color_v1dot0.sql
source /home/rahul/Documents/code/car-rental-system/Backend/cargo-backend/Persistence/Scripts/procedures/proc_get_make_v1dot0.sql
source /home/rahul/Documents/code/car-rental-system/Backend/cargo-backend/Persistence/Scripts/procedures/proc_get_user_details_v1dot0.sql
source /home/rahul/Documents/code/car-rental-system/Backend/cargo-backend/Persistence/Scripts/procedures/proc_get_variant_by_id_v1dot0.sql
source /home/rahul/Documents/code/car-rental-system/Backend/cargo-backend/Persistence/Scripts/procedures/proc_get_add_on_v1dot0.sql
source /home/rahul/Documents/code/car-rental-system/Backend/cargo-backend/Persistence/Scripts/procedures/proc_get_user_profile_v1dot0.sql
source /home/rahul/Documents/code/car-rental-system/Backend/cargo-backend/Persistence/Scripts/procedures/proc_create_payment_info_v1dot0.sql
source /home/rahul/Documents/code/car-rental-system/Backend/cargo-backend/Persistence/Scripts/procedures/proc_create_user_profile_v1dot0.sql
